### ISSUE TITLE
Error adding Google Ad Manager Credentials

### ISSUE THREAD

**Issue by keithnet** [Automattic/newspack-ads#835]
Trying to add credentials to Advertising --> Google Ad Manager. When I add Network Code # and upload JSON, I get:

Unrecoverable error
There has been a critical error on this website.

[Learn more about troubleshooting WordPress.](https://wordpress.org/documentation/article/faq-troubleshooting/)

I can't get rid of that error, which I see when trying to visit advertising wizard, without wiping option_value in _newspack_ads_gam_credentials database key.

This is in my logs:

[Mon Apr 22 14:15:54.175537 2024] [php:error] [pid 1561666]  PHP Fatal error:  Uncaught Error: Class "SoapClient" not found in /var/www/sitename/wp-content/plugins/newspack-ads/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php:32\nStack trace:\n#0 /var/www/sitename/wp-content/plugins/advanced-cron-manager/vendor/composer/ClassLoader.php(576): include()\n#1 /var/www/sitename/wp-content/plugins/advanced-cron-manager/vendor/composer/ClassLoader.php(427): Composer\\Autoload\\{closure}()\n#2 /var/www/sitename/wp-content/plugins/newspack-ads/vendor/googleads/googleads-php-lib/src/Google/AdsApi/AdManager/v202305/NetworkService.php(9): Composer\\Autoload\\ClassLoader->loadClass()\n#3 /var/www/sitename/wp-content/plugins/advanced-cron-manager/vendor/composer/ClassLoader.php(576): include('...')\n#4 /var/www/sitename/wp-content/plugins/advanced-cron-manager/vendor/composer/ClassLoader.php(427): Composer\\Autoload\\{closure}()\n#5 [internal function]: Composer\\Autoload\\ClassLoader->loadClass()\n#6 /var/www/sitename/wp-content/plugins/newspack-ads/vendor/googleads/googleads-php-lib/src/Google/AdsApi/AdManager/AdManagerServiceDescriptor.php(44): ReflectionClass->__construct()\n#7 /var/www/sitename/wp-content/plugins/newspack-ads/vendor/googleads/googleads-php-lib/src/Google/AdsApi/AdManager/AdManagerServices.php(60): Google\\AdsApi\\AdManager\\AdManagerServiceDescriptor->__construct()\n#8 /var/www/sitename/wp-content/plugins/newspack-ads/vendor/googleads/googleads-php-lib/src/Google/AdsApi/AdManager/v202305/ServiceFactory.php(351): Google\\AdsApi\\AdManager\\AdManagerServices->get()\n#9 /var/www/sitename/wp-content/plugins/newspack-ads/includes/providers/gam/api/class-api.php(282): Google\\AdsApi\\AdManager\\v202305\\ServiceFactory->createNetworkService()\n#10 /var/www/sitename/wp-content/plugins/newspack-ads/includes/providers/gam/api/class-api.php(317): Newspack_Ads\\Providers\\GAM\\Api->get_networks()\n#11 /var/www/sitename/wp-content/plugins/newspack-ads/includes/providers/gam/api/class-api.php(340): Newspack_Ads\\Providers\\GAM\\Api->get_network()\n#12 /var/www/sitename/wp-content/plugins/newspack-ads/includes/providers/gam/api/class-api.php(252): Newspack_Ads\\Providers\\GAM\\Api->get_network_code()\n#13 /var/www/sitename/wp-content/plugins/newspack-ads/includes/providers/gam/api/class-api.php(153): Newspack_Ads\\Providers\\GAM\\Api->get_session()\n#14 /var/www/sitename/wp-content/plugins/newspack-ads/includes/providers/gam/class-gam-model.php(119): Newspack_Ads\\Providers\\GAM\\Api->init()\n#15 /var/www/sitename/wp-content/plugins/newspack-ads/includes/providers/gam/class-gam-model.php(1181): Newspack_Ads\\Providers\\GAM_Model::get_api()\n#16 /var/www/sitename/wp-content/plugins/newspack-plugin/includes/configuration_managers/class-newspack-ads-configuration-manager.php(152): Newspack_Ads\\Providers\\GAM_Model::get_connection_status()\n#17 /var/www/sitename/wp-content/plugins/newspack-plugin/includes/wizards/class-advertising-wizard.php(446): Newspack\\Newspack_Ads_Configuration_Manager->get_gam_connection_status()\n#18 /var/www/sitename/wp-content/plugins/newspack-plugin/includes/wizards/class-advertising-wizard.php(408): Newspack\\Advertising_Wizard->get_services()\n#19 /var/www/sitename/wp-content/plugins/newspack-plugin/includes/wizards/class-advertising-wizard.php(296): Newspack\\Advertising_Wizard->retrieve_data()\n#20 /var/www/sitename/wp-includes/rest-api/class-wp-rest-server.php(1230): Newspack\\Advertising_Wizard->api_get_advertising()\n#21 /var/www/sitename/wp-includes/rest-api/class-wp-rest-server.php(1063): WP_REST_Server->respond_to_request()\n#22 /var/www/sitename/wp-includes/rest-api/class-wp-rest-server.php(439): WP_REST_Server->dispatch()\n#23 /var/www/sitename/wp-includes/rest-api.php(428): WP_REST_Server->serve_request()\n#24 /var/www/sitename/wp-includes/class-wp-hook.php(324): rest_api_loaded()\n#25 /var/www/sitename/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()\n#26 /var/www/sitename/wp-includes/plugin.php(565): WP_Hook->do_action()\n#27 /var/www/sitename/wp-includes/class-wp.php(418): do_action_ref_array()\n#28 /var/www/sitename/wp-includes/class-wp.php(813): WP->parse_request()\n#29 /var/www/sitename/wp-includes/functions.php(1336): WP->main()\n#30 /var/www/sitename/wp-blog-header.php(16): wp()\n#31 /var/www/sitename/index.php(17): require('...')\n#32 {main}\n  thrown in /var/www/sitename/wp-content/plugins/newspack-ads/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php on line 32, referer: https://www.sitename/wp-admin/admin.php?page=newspack-advertising-wizard

**Comment by keithnet** [comment]
php-soap wasn't installed on the server. adding that fixed this issue.
